import requests
import json
from pymongo import MongoClient
from model.response.TriggerResponse import TriggerResponse
from langchain.schema import Document
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import Chroma
import os
from dotenv import load_dotenv
from langchain_community.document_loaders import JSONLoader
# MongoDB connection setup
client = MongoClient('mongodb://localhost:27017/')  # Replace with your MongoDB URI
db = client['gen-ai']  
collection = db['response-logging']  

def save_trigger_response(trigger_response: TriggerResponse):
    # Convert the Pydantic model to a dictionary
    response_dict = trigger_response.dict(by_alias=True)
    
    # Insert the document into MongoDB
    result = collection.insert_one(response_dict)
    ## Attempting to store the same to the vector data base 
    # Load environment variables from .env
    docs= [
     Document(
        page_content=trigger_response.response,
        metadata={"response": "has the whole response of the json payload generated by the curl"}
    ),
    Document(
        page_content=trigger_response.request_name,
        metadata={"request_name": "name of the request"}
    ),
      Document(
        page_content=trigger_response.error_code,
        metadata={"response_code": "response error code for http request"}
    )
       
    ]

    load_dotenv()
    embedding_function = OpenAIEmbeddings()
    db = Chroma.from_documents(docs, embedding_function)
    # Dynamic Extraction of the Transactions Field
    response = trigger_response.response
    data_field = "data"
    transaction_field = "transactions"

    if isinstance(response, dict):
      data_field = "data"
      transaction_field = "transactions"

      if data_field in response and isinstance(response[data_field], dict):
        transactions = response[data_field].get(transaction_field, [])
      else:
        transactions = []
    else:
        transactions = []

    if transactions:
     available_fields = set(transactions[0].keys())
    else:
     available_fields = set()

    print("Available fields to monitor:")
    for index, field in enumerate(available_fields, start=1):
     print(f"{index}. {field}")


    # Step 2: Take User Input for Fields
    field_selection = input("enter the feilds to be monitered")
    selected_indices = [int(i.strip()) for i in field_selection.split(",")]

    # Map field index back to field names
    selected_fields = list(available_fields)
    user_selected_fields = [selected_fields[i - 1] for i in selected_indices if 0 < i <= len(selected_fields)]

    
    
    # Optionally, return the insertion result or the created ID
    return result.inserted_id

